- name: Copy ipmitool-fake package to the cluster nodes
  copy:
    src="{{ item }}"
    dest='/tmp/'
  with_fileglob: "ipmitool-fake-*.noarch.rpm"
  register: rc_copy

- name: install ipmitool-fake package
  yum:
    name="{{ item.dest }}"
    update_cache=yes
    state=present
  with_items: "{{ rc_copy.results }}"

